export const SELECT_RECIPE_SUCCESS = 'SELECT_RECIPE_SUCCESS';
export const SELECT_RECIPE_ERROR = 'SELECT_RECIPE_ERROR';
export const CLEAR_SELECTION = 'CLEAR_SELECTION';
export const LOAD_RECIPES_SUCCESS = 'LOAD_RECIPES_SUCCESS';
export const LOAD_RECIPES_ERROR = 'LOAD_RECIPES_ERROR';