export const SELECT_RECIPE_SUCCESS = 'SELECT_RECIPE_SUCCESS';
export const SELECT_RECIPE_ERROR = 'SELECT_RECIPE_ERROR';
export const CLEAR_SELECTION = 'CLEAR_SELECTION';
export const LOAD_RECIPES_SUCCESS = 'LOAD_RECIPES_SUCCESS';
export const LOAD_RECIPES_ERROR = 'LOAD_RECIPES_ERROR';
export const COLLAPSE_SIDEBAR = 'COLLAPSE_SIDEBAR';
export const EXPAND_SIDEBAR = 'EXPAND_SIDEBAR';
export const UPDATE_RECIPES_FILTER = 'UPDATE_RECIPES_FILTER';